"""Initial migration with all models

Revision ID: 426062e6808b
Revises: 
Create Date: 2026-01-01 14:49:34.687046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '426062e6808b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spreadsheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts_store', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('accounts_store_account_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('accounts_store_storage_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'storage', ['storage_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    with op.batch_alter_table('images_store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_images_store_task'))
        batch_op.drop_constraint(batch_op.f('images_store_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])

    with op.batch_alter_table('one_income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_one_income_task'))
        batch_op.drop_constraint(batch_op.f('one_income_total_income_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('one_income_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'total_income', ['total_income_id'], ['id'])
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])

    with op.batch_alter_table('payment_store', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_store_storage_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_store_payment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'storage', ['storage_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('show_in_portfolio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_thumbnail', sa.String(length=500), nullable=True))
        batch_op.drop_index(batch_op.f('idx_task_deadline'))
        batch_op.drop_index(batch_op.f('idx_task_is_done'))
        batch_op.drop_index(batch_op.f('idx_task_user_id'))
        batch_op.drop_constraint(batch_op.f('task_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))

    with op.batch_alter_table('whiteboard_elements', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_whiteboard_elements_board'))
        batch_op.drop_constraint(batch_op.f('whiteboard_elements_whiteboard_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'whiteboards', ['whiteboard_id'], ['id'])

    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_whiteboards_user'))
        batch_op.drop_constraint(batch_op.f('whiteboards_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workspace_manage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_workspace_manage_task'))
        batch_op.drop_constraint(batch_op.f('workspace_manage_workspace_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('workspace_manage_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workspace', ['workspace_id'], ['id'])
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_manage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workspace_manage_task_id_fkey'), 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('workspace_manage_workspace_id_fkey'), 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_workspace_manage_task'), ['task_id'], unique=False)

    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('whiteboards_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_whiteboards_user'), ['user_id'], unique=False)
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('whiteboard_elements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('whiteboard_elements_whiteboard_id_fkey'), 'whiteboards', ['whiteboard_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_whiteboard_elements_board'), ['whiteboard_id'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_task_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_task_is_done'), ['is_done'], unique=False)
        batch_op.create_index(batch_op.f('idx_task_deadline'), ['deadline'], unique=False)
        batch_op.drop_column('portfolio_thumbnail')
        batch_op.drop_column('show_in_portfolio')
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('payment_store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_store_payment_id_fkey'), 'payment', ['payment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('payment_store_storage_id_fkey'), 'storage', ['storage_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('one_income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('one_income_task_id_fkey'), 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('one_income_total_income_id_fkey'), 'total_income', ['total_income_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_one_income_task'), ['task_id'], unique=False)

    with op.batch_alter_table('images_store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('images_store_task_id_fkey'), 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_images_store_task'), ['task_id'], unique=False)

    with op.batch_alter_table('accounts_store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accounts_store_storage_id_fkey'), 'storage', ['storage_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('accounts_store_account_id_fkey'), 'account', ['account_id'], ['id'], ondelete='CASCADE')

    op.drop_table('spreadsheets')
    op.drop_table('documents')
    # ### end Alembic commands ###
