"""add completed_at to task

Revision ID: 9d43c887a8a6
Revises: 6226e98e30d6
Create Date: 2026-01-04 07:16:43.880507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d43c887a8a6'
down_revision = '6226e98e30d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chat_messages_team_created'))

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subtasks_task'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_task_project'))
        batch_op.drop_index(batch_op.f('idx_task_user_deadline'))

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_memberships_team'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_team_memberships_team'), ['team_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_task_user_deadline'), ['user_id', 'deadline'], unique=False)
        batch_op.create_index(batch_op.f('idx_task_project'), ['project_id'], unique=False)
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subtasks_task'), ['task_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chat_messages_team_created'), ['team_id', sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###
