"""add access_count to users

Revision ID: a1b2c3d4e5f6
Revises: 1e9bb9175548
Create Date: 2026-01-04 00:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1e9bb9175548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Column access_count already exists in the production DB, skip adding it
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('access_count', sa.Integer(), nullable=True))

    # Set default value for existing rows
    # op.execute("UPDATE users SET access_count = 0 WHERE access_count IS NULL")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_count')
    # ### end Alembic commands ###
